name: CI_Model_Training

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train_and_log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      # Menjalankan mlflow sebagai modul python
      - name: Run MLflow Project to Train Model
        run: python -m mlflow run . --env-manager local

      # Mengunggah artifact dari folder yang benar
      - name: Upload MLflow Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-results-artifact
          path: |
            membangun_model/mlruns/
            membangun_model/mlflow.db