name: Automatic Data Preprocessing

# Trigger: Workflow ini berjalan setiap kali ada push ke branch 'main'
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Memungkinkan trigger manual dari tab Actions

jobs:
  preprocess:
    # Menjalankan di server virtual Ubuntu terbaru
    runs-on: ubuntu-latest

    steps:
      # 1. Mengunduh kode dari repository Anda ke server
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Menyiapkan lingkungan Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Menginstal library yang dibutuhkan dari requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Menjalankan skrip preprocessing
      - name: Run data preprocessing script
        run: python automate_Farchan.py

      # 5. Mengunggah hasil preprocessing sebagai artifact
      - name: Upload processed dataset
        uses: actions/upload-artifact@v4
        with:
          # Nama artifact diubah agar lebih sesuai
          name: heart-disease-preprocessed-data 
          # Path diubah untuk mengunggah seluruh folder beserta isinya
          path: namadataset_preprocessing/