name: CI for Model Training

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train_and_log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt
  
      - name: Install MLflow
        run: pip install mlflow
  
      - name: Run MLflow Project to Train Model
        run: python -m mlflow run . --env-manager local

      # LANGKAH UNTUK MENJALANKAN MODEL (DIPISAHKAN)
      - name: Run MLflow Project to Train Model
        run: python -m mlflow run . --env-manager-local

      # Langkah Paling Penting untuk Diperiksa
      - name: Upload MLflow Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-results-artifact
          # Pastikan path ini benar. Tanda titik (.) berarti direktori saat ini.
          path: |
            membangun_model/titanic_preprocessing/mlruns/
            membangun_model/titanic_preprocessing/mlflow.db